cmd /c "h: && cd h:\jps2 && orgmode extractsrc jps2.org"
cmd /c "h: && cd h:\elmbyexample && orgmode multihtml elmbyexample.org target"
cmd /c "h: && cd h:\elmbyexample && orgmode extractsrc elmbyexample.org"
cmd /c "h: && cd h:\jps2 && orgmode latexbook jps2.org target/book/jps2.tex"
cmd /c "h: && cd h:\jps2 && orgmode multihtml jps2.org target/webnew"
cmd /c "h: && cd h:\public && orgmode latexslides folds.org folds.tex"
cmd /c "h: && cd h:\public && orgmode latexslides elm.org elm/elm.tex"
cmd /c "h: && cd h:\public && orgmode latexarticle elm.org elm/elmarticle.tex"
cmd /c "h: && cd h:\public && orgmode extractsrc elm.org"
cmd /c "h: && cd h:\public && orgmode extractsrc listfolds.org"
cmd /c "h: && cd h:\public && orgmode latexslides scalamonads.org scalamonads/scalamonads.tex"
cmd /c "h: && cd h:\public && orgmode extractsrc scalamonads.org"
rem cmd /c "h: && cd h:\jps2 && orgmode extractsrc2 jps2.org examples/script.scala && cd h:\jps2\examples"
